apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: amex-database
  namespace: amex
  labels:
    bakseter.net/backup-primary: true
spec:
  instances: 1
  storage:
    size: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1Gi
