apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amex
  namespace: amex
  annotations:
    tailscale.com/tags: tag:k8s,tag:media
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: amex-frontend
                port:
                  name: http

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: amex-backend
                port:
                  name: http
  tls:
    - hosts:
        - amex
